name: juz_amma_pe
description: "Aplikasi Hafalan Juz Amma"

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dio: ^5.8.0+1
  freezed_annotation: ^2.4.2
  flutter_bloc: ^9.1.0
  provider: ^6.1.2
  json_annotation: ^4.9.0
  flutter_hooks: ^0.21.2
  just_audio: ^0.9.46
  streaming_shared_preferences: ^2.0.0
  change_case: ^2.2.0

dev_dependencies:
  freezed: ^2.5.2
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.13
  json_serializable: ^6.9.0

flutter:
  uses-material-design: true

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
